import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import styles from '../styles/Home.module.css'

function hoge() {
  alert("foo");
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App Study</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          sign in
        </h1>

        <p className={styles.description}>
          ハリポテ
        </p>

        <div>
          <div>
            userID: <input></input>
          </div>
          <div>
            パスワード: <input></input>
          </div>
          <div>
            <button>sign in</button>
          </div>
        </div>

        <Link href="/newpage">
          <a>move new page</a>
        </Link>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
